### ISSUE TITLE
Extract and replace workflow/users with clinical:user-pages

### ISSUE THREAD

**Issue by awatson1978** [node-on-fhir/checklist-manifesto#15]

**Comment by bhautikp-egnaroinc** [comment]
which framework you have used?

**Comment by awatson1978** [comment]
There are a half-dozen apps in the Clinical Meteor project; all part of the Symptomatic Suite.  I'm extracting modules shared between each of them for consistency and use in future projects.  I'm making my own clinical framework.

**Comment by bhautikp-egnaroinc** [comment]
ohk i was asking for todos.

**Comment by awatson1978** [comment]
Removing user accounts from ChecklistManifesto MVP.  Closing.
