### ISSUE TITLE
The git line does not create the clinical-checklists folder

### ISSUE THREAD

**Issue by mozillanerd** [node-on-fhir/checklist-manifesto#20]
I have used you provided git command with the result that:
1. A git folder was created.
2. or my git folder was overwrittten,
3. or simple my git directory was opened and changed to.
Thanks

**Comment by awatson1978** [comment]
Ah, forgot to specify the webapp directory.  Just updated the readme to the following:

``` sh
# Should be as simple as cloning the repository...  
git clone https://github.com/awatson1978/clinical-checklists

# And then running it...
cd clinical-checklists/webapp
meteor
```
